name: Update teams data

on:
  workflow_dispatch:  # Оставляет возможность ручного запуска через сайт
  repository_dispatch:
    types: [run_scraper] # ВАЖНО: если в твоем запросе указан другой event_type, впиши его сюда вместо update-data

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests

      - name: Run parser
        run: python scraper.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add teams_data.json
          git diff --cached --quiet || git commit -m "chore: update teams_data $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
